### ISSUE TITLE
Lab intro checklist

### ISSUE THREAD

**Issue by leilaicruz** [T-Wisse/MEP_Thomas#11]
Checklist for the activities in the lab that you should cover

**Comment by leilaicruz** [comment]
- [ ] Solid and liquid media preparation (YPD,CSM,CSM-dropouts)
- [ ] Yeast incubation in solid and liquid media
- [ ] Inspecting the phenotype of your cells
   - [ ] Manual growth curves
   - [ ] Microscopy 
 - [ ] Strain construction
   - [ ] Yeast transformation (cloning)
     - [ ] primer design
     - [ ] DNA extraction
     - [ ] PCR
     - [ ] DNA gels
   - [ ] Mating
   - [ ] Yeast sporulation

**Comment by T-Wisse** [comment]
In the project we will not use mating or sporulation. Therefore I will not learn these techniques.
